secrets: secrets.yml
tasks:
  # Basic TV task
  tv-private:
    priority: 2
    template:
      - tv
      - notify
      - deluge_local
    interval: 15 minutes
    inputs:
      - rss: '{{ secrets.feed_urls.tv.btn }}'
      - rss: '{{ secrets.feed_urls.tv.tvchaos }}'
      - rss: '{{ secrets.feed_urls.tv.baconbits }}'
    manipulate:
      - description:
          remove: yes
      - title:
          replace:
            regexp: '\(\d{1,2} (Jan(?:uary)?|Feb(?:uary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sept(?:ember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?) \d{4}\)'
            format: ''

  # Tasmanites needs special handling
  tv-private-tasmanites:
    priority: 2
    template:
      - tv
      - notify
      - deluge_local
    interval: 15 minutes
    inputs:
      - rss: '{{ secrets.feed_urls.tv.tasmanites }}'
    manipulate:
      - description:
          remove: yes
    assume_quality: 480p sdtv

  # Add TV shows from the dropbox
  tv-dropbox:
    manual: yes
    priority: 2
    template:
      - tv
      - notify
      - deluge_local
    interval: 5 minutes
    inputs:
      - filesystem:
          path:
            - /home/torrent/drop/tv/
          recursive: yes
          mask: '*.torrent'
    assume_quality: 576p sdtv

  # Search the archive for missed shows
  tv-archive:
    interval: 4 hours
    manual: yes
    template:
      - tv
      - notify
      - deluge_local
    discover:
      what:
        - emit_series: yes
      from:
        - flexget_archive: [tv]

####

  # Search for NFL on BTN
  sport-nfl-private:
    priority: 3
    manual: yes
    template:
      - deluge_local
      - notify
    interval: 15 minutes
    inputs:
      - rss: '{{ secrets.feed_urls.sports.btn }}'
    regexp:
      accept:
        - 'NFL - .* - Super Bowl .*'
        - 'NFL - .* Championship .*'
        - 'NFL - .* Texans .*'
      reject:
        - Halftime
        - Commerials
        - Condensed
        - Foreign
      from: title
    quality: 720p+ webrip+
    set:
      label: sport
      movedone: '/srv/media/Sport/NFL/'

###

  movies-private:
    priority: 2
    template:
      - movies
      - notify
      - deluge_local
    interval: 1 hours
    inputs:
      - rss: '{{ secrets.feed_urls.movies.baconbits }}'
      - rss: '{{ secrets.feed_urls.movies.cinemageddon }}'

  movies-private-awesomehd:
    priority: 3
    template: 
      - movies
      - notify
      - deluge_local
    interval: 1 hours
    inputs:
      - rss: '{{ secrets.feed_urls.movies.awesomehd }}'
    manipulate:
      - title: 
          extract: 'MOVIE\: (.*)'
          replace:
            regexp: '/'
            format: '-'

  movies-private-awesomehd-seedbox:
    manual: yes
    priority: 1
    template:
      - deluge_seedbox
    interval: 5 minutes
    inputs:
      - rss: '{{ secrets.feed_urls.movies.awesomehd }}'
    manipulate:
      - title:
          extract: 'MOVIE\: (.*)'
          replace:
            regexp: '/'
            format: '-'
    regexp:
      accept:
        - '75% Freeleech'
    seen: local

  movies-public:
    manual: yes
    priority: 4
    template:
      - movies
      - notify
      - deluge_local
    interval: 4 hours
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz: verified
        - piratebay:
            category: 207
            sort_by: seeds

  movies-archive:
    interval: 1 hours
    template:
      - movies
      - notify
      - deluge_local
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - flexget_archive: [torrent, movies]

#####

  movies-seed_queue:
    priority: 1
    template:
      - no_global
    seen: local
    interval: 1 hours
    inputs:
      - imdb_list:
          user_id: '{{ secrets.services.imdb.user1 }}'
          list: watchlist
      - imdb_list:
          user_id: '{{ secrets.services.imdb.user2 }}'
          list: watchlist
    accept_all: yes
    movie_queue: 
      action: add
      quality: 720p+ bluray
    parsing:
      movie: guessit

  movies-populate-downloads:
    manual: yes
    disable: 
      - seen
      - seen_info_hash
      - seen_movies
    filesystem:
      - /srv/media/Movies
      - /srv/movie_archive/
    template: no_global
    movie_queue: accept
    make_rss: ~/movies.rss
    assume_quality: 1080p bluray

#####
# Magazines

  magazine-private:
    manual: yes
    template:
      - magazine
      - notify
      - deluge_local
    interval: 15 minutes
    inputs:
      - rss: '{{ secrets.feed_urls.magazines.baconbits }}'
    manipulate:
      - description:
          remove: yes

#####

templates:
  global:
    content_filter:
      reject:
        - password.txt
        - '*.rar'
        - '*.zip'
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
    cookies: /home/torrent/.flexget/cookies.txt
    pathscrub: windows
    magnets: no
    plugin_priority:
      piratebay: 140
    retry_failed: true
    pathscrub: windows
  notify:
    pushbullet:
      apikey:
        - '{{ secrets.services.pushbullet.user1 }}'
        - '{{ secrets.services.pushbullet.user2 }}'
      title: >
        {% if series_name is defined %}{{ tvdb_series_name|default(series_name, True) }} - {{ tvdb_ep_id|default(series_id, True) }}
        {% elif imdb_name is defined %}{{ imdb_name }} ({{ imdb_year }})
        {% else %}{{ title }}
        {% endif %}
      body: >
        {% if series_name is defined %}{{ tvdb_series_name|default(series_name, True) }} - {{ tvdb_ep_id|default(series_id, True) }}{% if tvdb_ep_name|default(False, True) %} - {{ tvdb_ep_name|replace('/', '-')|replace(':', ' - ') }}{% endif %}{% if quality is defined %} ({{ quality }}){% endif %}
        {% elif imdb_name is defined %}{{ imdb_name }} ({{ imdb_year }}){% if quality is defined %} ({{ quality }}){% endif %}
        {% else %}{{ title }}{% if quality is defined %} ({{ quality }}){% endif %}
        {% endif %}
  deluge_local:
    deluge:
      main_file_only: true
      ratio: 2.0
      removeatratio: true
      path: /home/torrent/downloads/
      movedone: /home/torrent/downloads/complete/
    free_space:
      path: /home/torrent/downloads/
      space: 1024
  deluge_seedbox:
    deluge:
      host: '{{ secrets.hosts.seedbox.hostname }}'
      username: '{{ secrets.hosts.seedbox.deluge_login }}'
      password: '{{ secrets.hosts.seedbox.deluge_password }}'
  tv:
    include: series.yml
    regexp:
      reject:
        - xAll
        - HDRip
    content_size:
      min: 50
      max: 3000
      strict: no
    thetvdb_lookup: yes
    set:
      content_filename: "{{ tvdb_series_name|default(series_name, True) }} - {{ tvdb_ep_id|default(series_id, True) }}{% if tvdb_ep_name|default(False, True) %} - {{ tvdb_ep_name|replace('/', '-')|replace(':', ' - ') }}{% endif %}{% if proper_count %} - Proper{% if proper_count > 1 %}{{ proper_count }}{% endif %}{% endif %}"
      label: tv
      movedone: /srv/media/TV/{{ tvdb_series_name|default(series_name, True) }}/Season {{ tvdb_season|default(series_season, True) }}
    archive:
      - torrent
      - tv
  movies:
    seen_movies: strict
    proper_movies: yes
    movie_queue: accept
    content_size:
      min: 700
      max: 10000
    set:
      content_filename: '{{ imdb_name | pathscrub | trim }} ({{ imdb_year }}){% if quality %} - {{ quality }}{% endif %}'
      label: movies
      movedone: /srv/movie_archive/{{ imdb_name | pathscrub | trim }} ({{ imdb_year}})
    regexp:
      reject:
        - 3d
        - extras
    archive:
      - torrent
      - movies
  magazine:
    set:
      label: magazine
      movedone: /srv/media/Magazines/
    regexp:
      accept:
        - ^Wired UK
        - ^Linux Voice
        - ^Linux User & Developer
        - ^Edge
        - ^GamesTM
        - ^Retro Gamer
    content_filter:
      require:
        - '*.pdf'
        - '*.epub'
        - '*.cbr'
